#
# Copyright (c) 2016-2017 Linagora
#
# This program/library is free software: you can redistribute it and/or modify
# it under the terms of the New BSD License (3-clause license).
#
# This program/library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the New BSD License (3-clause license)
# for more details.
#
# You should have received a copy of the New BSD License (3-clause license)
# along with this program/library; If not, see http://directory.fsf.org/wiki/License:BSD_3Clause/
# for the New BSD License (3-clause license).
#

rule "on-requests-nb-on-bc-soap-upper-5"
   # TODO: remove this sleep when Roboconf will be able to not launch a rule execution if one is already in progress.
   sleep period is 50s
   when
      check-requests-nb-on-bc-soap-upper-5
   then
      new-container-prov-vm
end