#!/bin/sh -x


OW2_NEXUS_URL_BASE=http://repository.ow2.org/nexus/service/local/artifact/maven/content
PETALS_GROUP_ID=org.ow2.petals
PETALS_COMMONS_DEB_ARTIFACT_ID=petals-commons-deb
PETALS_COMMONS_DEB_VERSION=LATEST
PETALS_COMMON_DEB_FILE=/tmp/${PETALS_COMMONS_DEB_ARTIFACT_ID}-${PETALS_COMMONS_DEB_VERSION}.deb
PETALS_REGISTRY_DEB_ARTIFACT_ID=petals-registry-overlay-deb
PETALS_REGISTRY_DEB_VERSION=LATEST
PETALS_REGISTRY_DEB_FILE=/tmp/${PETALS_REGISTRY_DEB_ARTIFACT_ID}-${PETALS_REGISTRY_DEB_VERSION}.deb
